-- -----------------------------------------------------
-- Datos para tabla `grados` (14 registros)
-- -----------------------------------------------------
INSERT INTO grados (nombre_grado, ciclo, turno, docente) VALUES
('Primero', 'Primer ciclo', 'Jornada completa', 'Carlos Mendoza'),
('Primero', 'Primer ciclo', 'Mañana', 'Ana Rodríguez'),
('Segundo', 'Primer ciclo', 'Jornada completa', 'Pedro Gómez'),
('Segundo', 'Primer ciclo', 'Mañana', 'Laura Martínez'),
('Tercero', 'Primer ciclo', 'Jornada completa', 'Luis Fernández'),
('Tercero', 'Primer ciclo', 'Mañana', 'María Sánchez'),
('Cuarto', 'Segundo ciclo', 'Jornada completa', 'Sofía Díaz'),
('Cuarto', 'Segundo ciclo', 'Mañana', 'Carmen López'),
('Quinto', 'Segundo ciclo', 'Jornada completa', 'Isabel Castro'),
('Quinto', 'Segundo ciclo', 'Mañana', 'Elena Ramírez'),
('Sexto', 'Segundo ciclo', 'Jornada completa', 'Lucía Torres'),
('Sexto', 'Segundo ciclo', 'Mañana', 'Adriana Romero'),
('Séptimo', 'Segundo ciclo', 'Jornada completa', 'Patricia Núñez'),
('Séptimo', 'Segundo ciclo', 'Mañana', 'Andrea Molina');

-- -----------------------------------------------------
-- Datos para tabla `estudiantes` (253 registros)
-- -----------------------------------------------------
INSERT INTO estudiantes (id_grado, nombre, apellido, edad, direccion, nombre_madre, nombre_padre, hermano_en_escuela) VALUES
-- Grado 1: Jornada completa (5 varones, 5 mujeres)
(1, 'Juan', 'García', 6, 'Calle 123', 'Laura García', 'Carlos García', 0),
(1, 'Carlos', 'López', 6, 'Calle 456', 'Ana López', 'José López', 1),
(1, 'Pedro', 'Martínez', 6, 'Calle 789', 'María Martínez', 'Miguel Martínez', 0),
(1, 'Luis', 'Sánchez', 6, 'Calle 101', 'Sofía Sánchez', 'Javier Sánchez', 1),
(1, 'Miguel', 'Pérez', 6, 'Calle 112', 'Carmen Pérez', 'Alejandro Pérez', 0),
(1, 'Ana', 'Rodríguez', 6, 'Calle 131', 'Isabel Rodríguez', 'Daniel Rodríguez', 1),
(1, 'María', 'Hernández', 6, 'Calle 415', 'Lucía Hernández', 'Roberto Hernández', 0),
(1, 'Sofía', 'Díaz', 6, 'Calle 161', 'Marta Díaz', 'Fernando Díaz', 1),
(1, 'Laura', 'Torres', 6, 'Calle 617', 'Elena Torres', 'Rafael Torres', 0),
(1, 'Carmen', 'Fernández', 6, 'Calle 819', 'Paula Fernández', 'Francisco Fernández', 1),

-- Grado 2: Jornada completa (4 varones, 9 mujeres)
(3, 'Jorge', 'Ramírez', 7, 'Calle 202', 'Patricia Ramírez', 'Juan Ramírez', 1),
(3, 'Diego', 'Cruz', 7, 'Calle 303', 'Adriana Cruz', 'Pedro Cruz', 0),
(3, 'Andrés', 'Ortiz', 7, 'Calle 404', 'Andrea Ortiz', 'Luis Ortiz', 1),
(3, 'Fernando', 'Morales', 7, 'Calle 505', 'Silvia Morales', 'Carlos Morales', 0),
(3, 'Lucía', 'Gómez', 7, 'Calle 606', 'Elena Gómez', 'Miguel Gómez', 1),
(3, 'Elena', 'Ruiz', 7, 'Calle 707', 'Carmen Ruiz', 'Jorge Ruiz', 0),
(3, 'Isabel', 'Jiménez', 7, 'Calle 808', 'Laura Jiménez', 'Diego Jiménez', 1),
(3, 'Patricia', 'Serrano', 7, 'Calle 909', 'Sofía Serrano', 'Andrés Serrano', 0),
(3, 'Adriana', 'Romero', 7, 'Calle 111', 'María Romero', 'Fernando Romero', 1),
(3, 'Silvia', 'Torres', 7, 'Calle 222', 'Lucía Torres', 'Javier Torres', 0),
(3, 'Andrea', 'Navarro', 7, 'Calle 333', 'Elena Navarro', 'Carlos Navarro', 1),
(3, 'Clara', 'Molina', 7, 'Calle 444', 'Patricia Molina', 'Pedro Molina', 0),
(3, 'Rosa', 'Ortega', 7, 'Calle 555', 'Adriana Ortega', 'Luis Ortega', 1),

-- Grado 3: Jornada completa (6 varones, 14 mujeres)
(5, 'Roberto', 'Vargas', 8, 'Calle 666', 'Ana Vargas', 'Roberto Vargas Sr', 0),
(5, 'Francisco', 'Reyes', 8, 'Calle 777', 'María Reyes', 'Francisco Reyes Sr', 1),
(5, 'Javier', 'Campos', 8, 'Calle 888', 'Sofía Campos', 'Javier Campos Sr', 0),
(5, 'Daniel', 'Guerrero', 8, 'Calle 999', 'Carmen Guerrero', 'Daniel Guerrero Sr', 1),
(5, 'Alejandro', 'Santos', 8, 'Calle 121', 'Laura Santos', 'Alejandro Santos Sr', 0),
(5, 'Rafael', 'Castro', 8, 'Calle 232', 'Isabel Castro', 'Rafael Castro Sr', 1),
(5, 'Marta', 'Lorenzo', 8, 'Calle 343', 'Patricia Lorenzo', 'Miguel Lorenzo', 0),
(5, 'Nuria', 'Herrera', 8, 'Calle 454', 'Adriana Herrera', 'Carlos Herrera', 1),
(5, 'Cristina', 'Iglesias', 8, 'Calle 565', 'Andrea Iglesias', 'Jorge Iglesias', 0),
(5, 'Ángela', 'Delgado', 8, 'Calle 676', 'Silvia Delgado', 'Fernando Delgado', 1),
(5, 'Eva', 'Ramírez', 8, 'Calle 787', 'Clara Ramírez', 'Diego Ramírez', 0),
(5, 'Julia', 'Méndez', 8, 'Calle 898', 'Rosa Méndez', 'Andrés Méndez', 1),
(5, 'Monica', 'Gallego', 8, 'Calle 919', 'Nuria Gallego', 'Javier Gallego', 0),
(5, 'Alicia', 'Pascual', 8, 'Calle 122', 'Cristina Pascual', 'Alejandro Pascual', 1),
(5, 'Sara', 'Calvo', 8, 'Calle 233', 'Ángela Calvo', 'Daniel Calvo', 0),
(5, 'Verónica', 'León', 8, 'Calle 344', 'Eva León', 'Rafael León', 1),
(5, 'Lidia', 'Marín', 8, 'Calle 455', 'Julia Marín', 'Francisco Marín', 0),
(5, 'Natalia', 'Cabrera', 8, 'Calle 566', 'Monica Cabrera', 'Roberto Cabrera', 1),
(5, 'Beatriz', 'Rivas', 8, 'Calle 677', 'Alicia Rivas', 'Jorge Rivas', 0),
(5, 'Alba', 'Soto', 8, 'Calle 788', 'Sara Soto', 'Pedro Soto', 1),

-- Grado 4: Jornada completa (8 varones, 11 mujeres)
(7, 'Sergio', 'Vega', 9, 'Calle 899', 'Silvia Vega', 'Sergio Vega Sr', 1),
(7, 'Alberto', 'Fuentes', 9, 'Calle 911', 'Clara Fuentes', 'Alberto Fuentes Sr', 0),
(7, 'Ricardo', 'Blanco', 9, 'Calle 122', 'Rosa Blanco', 'Ricardo Blanco Sr', 1),
(7, 'Guillermo', 'Ramos', 9, 'Calle 233', 'Nuria Ramos', 'Guillermo Ramos Sr', 0),
(7, 'Óscar', 'Gil', 9, 'Calle 344', 'Cristina Gil', 'Óscar Gil Sr', 1),
(7, 'Enrique', 'Bravo', 9, 'Calle 455', 'Ángela Bravo', 'Enrique Bravo Sr', 0),
(7, 'Víctor', 'Gallardo', 9, 'Calle 566', 'Eva Gallardo', 'Víctor Gallardo Sr', 1),
(7, 'Adrián', 'Vázquez', 9, 'Calle 677', 'Julia Vázquez', 'Adrián Vázquez Sr', 0),
(7, 'Inés', 'Caballero', 9, 'Calle 788', 'Monica Caballero', 'Sergio Caballero', 1),
(7, 'Olga', 'Roldán', 9, 'Calle 899', 'Alicia Roldán', 'Alberto Roldán', 0),
(7, 'Irene', 'Quiroga', 9, 'Calle 911', 'Sara Quiroga', 'Ricardo Quiroga', 1),
(7, 'Marina', 'Pardo', 9, 'Calle 123', 'Verónica Pardo', 'Guillermo Pardo', 0),
(7, 'Esther', 'Salas', 9, 'Calle 234', 'Lidia Salas', 'Óscar Salas', 1),
(7, 'Pilar', 'Peña', 9, 'Calle 345', 'Natalia Peña', 'Enrique Peña', 0),
(7, 'Jimena', 'Riera', 9, 'Calle 456', 'Beatriz Riera', 'Víctor Riera', 1),
(7, 'Raquel', 'Vidal', 9, 'Calle 567', 'Alba Vidal', 'Adrián Vidal', 0),
(7, 'Teresa', 'Sáez', 9, 'Calle 678', 'Inés Sáez', 'Sergio Sáez', 1),
(7, 'Angela', 'Mora', 9, 'Calle 789', 'Olga Mora', 'Alberto Mora', 0),
(7, 'Rocío', 'Carrasco', 9, 'Calle 890', 'Irene Carrasco', 'Ricardo Carrasco', 1),

-- Grado 5: Jornada completa (8 varones, 11 mujeres)
(9, 'Pablo', 'Santana', 10, 'Calle 901', 'Marina Santana', 'Pablo Santana Sr', 0),
(9, 'Santiago', 'Pacheco', 10, 'Calle 112', 'Esther Pacheco', 'Santiago Pacheco Sr', 1),
(9, 'Joaquín', 'Lara', 10, 'Calle 223', 'Pilar Lara', 'Joaquín Lara Sr', 0),
(9, 'Martín', 'Rocha', 10, 'Calle 334', 'Jimena Rocha', 'Martín Rocha Sr', 1),
(9, 'Álvaro', 'Valero', 10, 'Calle 445', 'Raquel Valero', 'Álvaro Valero Sr', 0),
(9, 'Gustavo', 'Camacho', 10, 'Calle 556', 'Teresa Camacho', 'Gustavo Camacho Sr', 1),
(9, 'Emilio', 'Villar', 10, 'Calle 667', 'Angela Villar', 'Emilio Villar Sr', 0),
(9, 'Héctor', 'Aguilera', 10, 'Calle 778', 'Rocío Aguilera', 'Héctor Aguilera Sr', 1),
(9, 'Victoria', 'Barbero', 10, 'Calle 889', 'Marina Barbero', 'Pablo Barbero', 0),
(9, 'Nuria', 'Rey', 10, 'Calle 990', 'Esther Rey', 'Santiago Rey', 1),
(9, 'Cristina', 'Ríos', 10, 'Calle 101', 'Pilar Ríos', 'Joaquín Ríos', 0),
(9, 'Ángela', 'Acosta', 10, 'Calle 212', 'Jimena Acosta', 'Martín Acosta', 1),
(9, 'Eva', 'Benitez', 10, 'Calle 323', 'Raquel Benitez', 'Álvaro Benitez', 0),
(9, 'Julia', 'Crespo', 10, 'Calle 434', 'Teresa Crespo', 'Gustavo Crespo', 1),
(9, 'Monica', 'Domingo', 10, 'Calle 545', 'Angela Domingo', 'Emilio Domingo', 0),
(9, 'Alicia', 'Ferrer', 10, 'Calle 656', 'Rocío Ferrer', 'Héctor Ferrer', 1),
(9, 'Sara', 'Galán', 10, 'Calle 767', 'Victoria Galán', 'Pablo Galán', 0),
(9, 'Verónica', 'Hidalgo', 10, 'Calle 878', 'Nuria Hidalgo', 'Santiago Hidalgo', 1),
(9, 'Lidia', 'Jurado', 10, 'Calle 989', 'Cristina Jurado', 'Joaquín Jurado', 0),

-- Grado 6: Jornada completa (9 varones, 9 mujeres)
(11, 'Ignacio', 'Mas', 11, 'Calle 111', 'Ángela Mas', 'Ignacio Mas Sr', 1),
(11, 'Marcos', 'Mateo', 11, 'Calle 222', 'Eva Mateo', 'Marcos Mateo Sr', 0),
(11, 'Julián', 'Mayo', 11, 'Calle 333', 'Julia Mayo', 'Julián Mayo Sr', 1),
(11, 'Rodrigo', 'Millán', 11, 'Calle 444', 'Monica Millán', 'Rodrigo Millán Sr', 0),
(11, 'Federico', 'Mira', 11, 'Calle 555', 'Alicia Mira', 'Federico Mira Sr', 1),
(11, 'Hugo', 'Moya', 11, 'Calle 666', 'Sara Moya', 'Hugo Moya Sr', 0),
(11, 'Iván', 'Nieto', 11, 'Calle 777', 'Verónica Nieto', 'Iván Nieto Sr', 1),
(11, 'Gabriel', 'Ojeda', 11, 'Calle 888', 'Lidia Ojeda', 'Gabriel Ojeda Sr', 0),
(11, 'Raúl', 'Oliva', 11, 'Calle 999', 'Natalia Oliva', 'Raúl Oliva Sr', 1),
(11, 'Beatriz', 'Peral', 11, 'Calle 121', 'Beatriz Peral', 'Ignacio Peral', 0),
(11, 'Alba', 'Piñeiro', 11, 'Calle 232', 'Alba Piñeiro', 'Marcos Piñeiro', 1),
(11, 'Clara', 'Quesada', 11, 'Calle 343', 'Clara Quesada', 'Julián Quesada', 0),
(11, 'Rosa', 'Redondo', 11, 'Calle 454', 'Rosa Redondo', 'Rodrigo Redondo', 1),
(11, 'Nuria', 'Robles', 11, 'Calle 565', 'Nuria Robles', 'Federico Robles', 0),
(11, 'Cristina', 'Rosado', 11, 'Calle 676', 'Cristina Rosado', 'Hugo Rosado', 1),
(11, 'Ángela', 'Rubio', 11, 'Calle 787', 'Ángela Rubio', 'Iván Rubio', 0),
(11, 'Eva', 'Salazar', 11, 'Calle 898', 'Eva Salazar', 'Gabriel Salazar', 1),
(11, 'Julia', 'Téllez', 11, 'Calle 919', 'Julia Téllez', 'Raúl Téllez', 0),

-- Grado 7: Jornada completa (12 varones, 6 mujeres)
(13, 'Mario', 'Sola', 12, 'Calle 122', 'Monica Sola', 'Mario Sola Sr', 0),
(13, 'Roberto', 'Solano', 12, 'Calle 233', 'Alicia Solano', 'Roberto Solano Sr', 1),
(13, 'Francisco', 'Toro', 12, 'Calle 344', 'Sara Toro', 'Francisco Toro Sr', 0),
(13, 'Javier', 'Trujillo', 12, 'Calle 455', 'Verónica Trujillo', 'Javier Trujillo Sr', 1),
(13, 'Daniel', 'Valverde', 12, 'Calle 566', 'Lidia Valverde', 'Daniel Valverde Sr', 0),
(13, 'Alejandro', 'Varela', 12, 'Calle 677', 'Natalia Varela', 'Alejandro Varela Sr', 1),
(13, 'Rafael', 'Vega', 12, 'Calle 788', 'Beatriz Vega', 'Rafael Vega Sr', 0),
(13, 'Sergio', 'Yáñez', 12, 'Calle 899', 'Alba Yáñez', 'Sergio Yáñez Sr', 1),
(13, 'Alberto', 'Zambrano', 12, 'Calle 911', 'Clara Zambrano', 'Alberto Zambrano Sr', 0),
(13, 'Ricardo', 'Zapata', 12, 'Calle 123', 'Rosa Zapata', 'Ricardo Zapata Sr', 1),
(13, 'Guillermo', 'Zurita', 12, 'Calle 234', 'Nuria Zurita', 'Guillermo Zurita Sr', 0),
(13, 'Óscar', 'Arias', 12, 'Calle 345', 'Cristina Arias', 'Óscar Arias Sr', 1),
(13, 'Marina', 'Bermúdez', 12, 'Calle 456', 'Ángela Bermúdez', 'Mario Bermúdez', 0),
(13, 'Esther', 'Castaño', 12, 'Calle 567', 'Eva Castaño', 'Roberto Castaño', 1),
(13, 'Pilar', 'Cordero', 12, 'Calle 678', 'Julia Cordero', 'Francisco Cordero', 0),
(13, 'Jimena', 'Espejo', 12, 'Calle 789', 'Monica Espejo', 'Javier Espejo', 1),
(13, 'Raquel', 'Frías', 12, 'Calle 890', 'Alicia Frías', 'Daniel Frías', 0),
(13, 'Teresa', 'Gálvez', 12, 'Calle 901', 'Sara Gálvez', 'Alejandro Gálvez', 1),

-- Grado 1: Mañana (7 varones, 11 mujeres)
(2, 'Jorge', 'Herrera', 6, 'Calle 112', 'Patricia Herrera', 'Jorge Herrera Sr', 1),
(2, 'Diego', 'Mendoza', 6, 'Calle 223', 'Adriana Mendoza', 'Diego Mendoza Sr', 0),
(2, 'Andrés', 'Pons', 6, 'Calle 334', 'Andrea Pons', 'Andrés Pons Sr', 1),
(2, 'Fernando', 'Rovira', 6, 'Calle 445', 'Silvia Rovira', 'Fernando Rovira Sr', 0),
(2, 'Pablo', 'Sola', 6, 'Calle 556', 'Marina Sola', 'Pablo Sola Sr', 1),
(2, 'Santiago', 'Talavera', 6, 'Calle 667', 'Esther Talavera', 'Santiago Talavera Sr', 0),
(2, 'Joaquín', 'Ureña', 6, 'Calle 778', 'Pilar Ureña', 'Joaquín Ureña Sr', 1),
(2, 'Sara', 'Vicente', 6, 'Calle 889', 'Verónica Vicente', 'Jorge Vicente', 0),
(2, 'Verónica', 'Abril', 6, 'Calle 990', 'Lidia Abril', 'Diego Abril', 1),
(2, 'Lidia', 'Ballesteros', 6, 'Calle 101', 'Natalia Ballesteros', 'Andrés Ballesteros', 0),
(2, 'Natalia', 'Calderón', 6, 'Calle 212', 'Beatriz Calderón', 'Fernando Calderón', 1),
(2, 'Beatriz', 'Duarte', 6, 'Calle 323', 'Alba Duarte', 'Pablo Duarte', 0),
(2, 'Alba', 'Espinosa', 6, 'Calle 434', 'Clara Espinosa', 'Santiago Espinosa', 1),
(2, 'Clara', 'Ferrero', 6, 'Calle 545', 'Rosa Ferrero', 'Joaquín Ferrero', 0),
(2, 'Rosa', 'Garmendia', 6, 'Calle 656', 'Nuria Garmendia', 'Jorge Garmendia', 1),
(2, 'Nuria', 'Hernando', 6, 'Calle 767', 'Cristina Hernando', 'Diego Hernando', 0),
(2, 'Cristina', 'Ibarra', 6, 'Calle 878', 'Ángela Ibarra', 'Andrés Ibarra', 1),
(2, 'Ángela', 'Jáuregui', 6, 'Calle 989', 'Eva Jáuregui', 'Fernando Jáuregui', 0),

-- Grado 2: Mañana (12 varones, 8 mujeres)
(4, 'Martín', 'Lago', 7, 'Calle 111', 'Ángela Lago', 'Martín Lago Sr', 1),
(4, 'Álvaro', 'León', 7, 'Calle 222', 'Eva León', 'Álvaro León Sr', 0),
(4, 'Gustavo', 'Linares', 7, 'Calle 333', 'Julia Linares', 'Gustavo Linares Sr', 1),
(4, 'Emilio', 'Llorente', 7, 'Calle 444', 'Monica Llorente', 'Emilio Llorente Sr', 0),
(4, 'Héctor', 'Madrid', 7, 'Calle 555', 'Alicia Madrid', 'Héctor Madrid Sr', 1),
(4, 'Ignacio', 'Márquez', 7, 'Calle 666', 'Sara Márquez', 'Ignacio Márquez Sr', 0),
(4, 'Marcos', 'Martín', 7, 'Calle 777', 'Verónica Martín', 'Marcos Martín Sr', 1),
(4, 'Julián', 'Medina', 7, 'Calle 888', 'Lidia Medina', 'Julián Medina Sr', 0),
(4, 'Rodrigo', 'Méndez', 7, 'Calle 999', 'Natalia Méndez', 'Rodrigo Méndez Sr', 1),
(4, 'Federico', 'Molina', 7, 'Calle 121', 'Beatriz Molina', 'Federico Molina Sr', 0),
(4, 'Hugo', 'Montoro', 7, 'Calle 232', 'Alba Montoro', 'Hugo Montoro Sr', 1),
(4, 'Iván', 'Morales', 7, 'Calle 343', 'Clara Morales', 'Iván Morales Sr', 0),
(4, 'Eva', 'Navas', 7, 'Calle 454', 'Rosa Navas', 'Martín Navas', 1),
(4, 'Julia', 'Ocaña', 7, 'Calle 565', 'Nuria Ocaña', 'Álvaro Ocaña', 0),
(4, 'Monica', 'Olmedo', 7, 'Calle 676', 'Cristina Olmedo', 'Gustavo Olmedo', 1),
(4, 'Alicia', 'Ortega', 7, 'Calle 787', 'Ángela Ortega', 'Emilio Ortega', 0),
(4, 'Sara', 'Pacheco', 7, 'Calle 898', 'Eva Pacheco', 'Héctor Pacheco', 1),
(4, 'Verónica', 'Palacios', 7, 'Calle 919', 'Julia Palacios', 'Ignacio Palacios', 0),
(4, 'Lidia', 'Quesada', 7, 'Calle 122', 'Monica Quesada', 'Marcos Quesada', 1),
(4, 'Natalia', 'Quintero', 7, 'Calle 233', 'Alicia Quintero', 'Julián Quintero', 0),

-- Grado 3: Mañana (9 varones, 12 mujeres)
(6, 'Gabriel', 'Reyes', 8, 'Calle 344', 'Sara Reyes', 'Gabriel Reyes Sr', 1),
(6, 'Raúl', 'Ríos', 8, 'Calle 455', 'Verónica Ríos', 'Raúl Ríos Sr', 0),
(6, 'Mario', 'Roca', 8, 'Calle 566', 'Lidia Roca', 'Mario Roca Sr', 1),
(6, 'Roberto', 'Rodríguez', 8, 'Calle 677', 'Natalia Rodríguez', 'Roberto Rodríguez Sr', 0),
(6, 'Francisco', 'Romero', 8, 'Calle 788', 'Beatriz Romero', 'Francisco Romero Sr', 1),
(6, 'Javier', 'Ros', 8, 'Calle 899', 'Alba Ros', 'Javier Ros Sr', 0),
(6, 'Daniel', 'Rubio', 8, 'Calle 911', 'Clara Rubio', 'Daniel Rubio Sr', 1),
(6, 'Alejandro', 'Ruiz', 8, 'Calle 123', 'Rosa Ruiz', 'Alejandro Ruiz Sr', 0),
(6, 'Rafael', 'Sáenz', 8, 'Calle 234', 'Nuria Sáenz', 'Rafael Sáenz Sr', 1),
(6, 'Inés', 'Salgado', 8, 'Calle 345', 'Cristina Salgado', 'Gabriel Salgado', 0),
(6, 'Olga', 'Sánchez', 8, 'Calle 456', 'Ángela Sánchez', 'Raúl Sánchez', 1),
(6, 'Irene', 'Santos', 8, 'Calle 567', 'Eva Santos', 'Mario Santos', 0),
(6, 'Marina', 'Sanz', 8, 'Calle 678', 'Julia Sanz', 'Roberto Sanz', 1),
(6, 'Esther', 'Segura', 8, 'Calle 789', 'Monica Segura', 'Francisco Segura', 0),
(6, 'Pilar', 'Sola', 8, 'Calle 890', 'Alicia Sola', 'Javier Sola', 1),
(6, 'Jimena', 'Soler', 8, 'Calle 901', 'Sara Soler', 'Daniel Soler', 0),
(6, 'Raquel', 'Soto', 8, 'Calle 112', 'Verónica Soto', 'Alejandro Soto', 1),
(6, 'Teresa', 'Tejero', 8, 'Calle 223', 'Lidia Tejero', 'Rafael Tejero', 0),
(6, 'Angela', 'Téllez', 8, 'Calle 334', 'Natalia Téllez', 'Gabriel Téllez', 1),
(6, 'Rocío', 'Tomas', 8, 'Calle 445', 'Beatriz Tomas', 'Raúl Tomas', 0),
(6, 'Victoria', 'Valero', 8, 'Calle 556', 'Alba Valero', 'Mario Valero', 1),

-- Grado 4: Mañana (12 varones, 7 mujeres)
(8, 'Sergio', 'Valls', 9, 'Calle 667', 'Clara Valls', 'Sergio Valls Sr', 0),
(8, 'Alberto', 'Vargas', 9, 'Calle 778', 'Rosa Vargas', 'Alberto Vargas Sr', 1),
(8, 'Ricardo', 'Vázquez', 9, 'Calle 889', 'Nuria Vázquez', 'Ricardo Vázquez Sr', 0),
(8, 'Guillermo', 'Vega', 9, 'Calle 990', 'Cristina Vega', 'Guillermo Vega Sr', 1),
(8, 'Óscar', 'Velasco', 9, 'Calle 101', 'Ángela Velasco', 'Óscar Velasco Sr', 0),
(8, 'Enrique', 'Vicente', 9, 'Calle 212', 'Eva Vicente', 'Enrique Vicente Sr', 1),
(8, 'Víctor', 'Vidal', 9, 'Calle 323', 'Julia Vidal', 'Víctor Vidal Sr', 0),
(8, 'Adrián', 'Villa', 9, 'Calle 434', 'Monica Villa', 'Adrián Villa Sr', 1),
(8, 'Ignacio', 'Villar', 9, 'Calle 545', 'Alicia Villar', 'Ignacio Villar Sr', 0),
(8, 'Marcos', 'Yuste', 9, 'Calle 656', 'Sara Yuste', 'Marcos Yuste Sr', 1),
(8, 'Julián', 'Zabala', 9, 'Calle 767', 'Verónica Zabala', 'Julián Zabala Sr', 0),
(8, 'Rodrigo', 'Zamora', 9, 'Calle 878', 'Lidia Zamora', 'Rodrigo Zamora Sr', 1),
(8, 'Marina', 'Zapata', 9, 'Calle 989', 'Natalia Zapata', 'Sergio Zapata', 0),
(8, 'Esther', 'Zaragoza', 9, 'Calle 111', 'Beatriz Zaragoza', 'Alberto Zaragoza', 1),
(8, 'Pilar', 'Zúñiga', 9, 'Calle 222', 'Alba Zúñiga', 'Ricardo Zúñiga', 0),
(8, 'Jimena', 'Acedo', 9, 'Calle 333', 'Clara Acedo', 'Guillermo Acedo', 1),
(8, 'Raquel', 'Aguado', 9, 'Calle 444', 'Rosa Aguado', 'Óscar Aguado', 0),
(8, 'Teresa', 'Alcaraz', 9, 'Calle 555', 'Nuria Alcaraz', 'Enrique Alcaraz', 1),
(8, 'Angela', 'Alfaro', 9, 'Calle 666', 'Cristina Alfaro', 'Víctor Alfaro', 0),

-- Grado 5: Mañana (13 varones, 6 mujeres)
(10, 'Federico', 'Amador', 10, 'Calle 777', 'Ángela Amador', 'Federico Amador Sr', 1),
(10, 'Hugo', 'Aranda', 10, 'Calle 888', 'Eva Aranda', 'Hugo Aranda Sr', 0),
(10, 'Iván', 'Arias', 10, 'Calle 999', 'Julia Arias', 'Iván Arias Sr', 1),
(10, 'Gabriel', 'Arroyo', 10, 'Calle 121', 'Monica Arroyo', 'Gabriel Arroyo Sr', 0),
(10, 'Raúl', 'Avilés', 10, 'Calle 232', 'Alicia Avilés', 'Raúl Avilés Sr', 1),
(10, 'Mario', 'Báez', 10, 'Calle 343', 'Sara Báez', 'Mario Báez Sr', 0),
(10, 'Roberto', 'Ballester', 10, 'Calle 454', 'Verónica Ballester', 'Roberto Ballester Sr', 1),
(10, 'Francisco', 'Barragán', 10, 'Calle 565', 'Lidia Barragán', 'Francisco Barragán Sr', 0),
(10, 'Javier', 'Beltrán', 10, 'Calle 676', 'Natalia Beltrán', 'Javier Beltrán Sr', 1),
(10, 'Daniel', 'Benito', 10, 'Calle 787', 'Beatriz Benito', 'Daniel Benito Sr', 0),
(10, 'Alejandro', 'Bernal', 10, 'Calle 898', 'Alba Bernal', 'Alejandro Bernal Sr', 1),
(10, 'Rafael', 'Blasco', 10, 'Calle 919', 'Clara Blasco', 'Rafael Blasco Sr', 0),
(10, 'Sergio', 'Bueno', 10, 'Calle 122', 'Rosa Bueno', 'Sergio Bueno Sr', 1),
(10, 'Eva', 'Cabrera', 10, 'Calle 233', 'Nuria Cabrera', 'Federico Cabrera', 0),
(10, 'Julia', 'Calatayud', 10, 'Calle 344', 'Cristina Calatayud', 'Hugo Calatayud', 1),
(10, 'Monica', 'Cámara', 10, 'Calle 455', 'Ángela Cámara', 'Iván Cámara', 0),
(10, 'Alicia', 'Cano', 10, 'Calle 566', 'Eva Cano', 'Gabriel Cano', 1),
(10, 'Sara', 'Cantón', 10, 'Calle 677', 'Julia Cantón', 'Raúl Cantón', 0),
(10, 'Verónica', 'Carretero', 10, 'Calle 788', 'Monica Carretero', 'Mario Carretero', 1),

-- Grado 6: Mañana (8 varones, 12 mujeres)
(12, 'Alberto', 'Castellanos', 11, 'Calle 899', 'Alicia Castellanos', 'Alberto Castellanos Sr', 0),
(12, 'Ricardo', 'Cepeda', 11, 'Calle 911', 'Sara Cepeda', 'Ricardo Cepeda Sr', 1),
(12, 'Guillermo', 'Cerro', 11, 'Calle 123', 'Verónica Cerro', 'Guillermo Cerro Sr', 0),
(12, 'Óscar', 'Cobo', 11, 'Calle 234', 'Lidia Cobo', 'Óscar Cobo Sr', 1),
(12, 'Enrique', 'Collado', 11, 'Calle 345', 'Natalia Collado', 'Enrique Collado Sr', 0),
(12, 'Víctor', 'Cordón', 11, 'Calle 456', 'Beatriz Cordón', 'Víctor Cordón Sr', 1),
(12, 'Adrián', 'Corral', 11, 'Calle 567', 'Alba Corral', 'Adrián Corral Sr', 0),
(12, 'Ignacio', 'Cortés', 11, 'Calle 678', 'Clara Cortés', 'Ignacio Cortés Sr', 1),
(12, 'Beatriz', 'Cuéllar', 11, 'Calle 789', 'Rosa Cuéllar', 'Alberto Cuéllar', 0),
(12, 'Alba', 'Chacón', 11, 'Calle 890', 'Nuria Chacón', 'Ricardo Chacón', 1),
(12, 'Clara', 'Delgado', 11, 'Calle 901', 'Cristina Delgado', 'Guillermo Delgado', 0),
(12, 'Rosa', 'Díaz', 11, 'Calle 112', 'Ángela Díaz', 'Óscar Díaz', 1),
(12, 'Nuria', 'Dominguez', 11, 'Calle 223', 'Eva Dominguez', 'Enrique Dominguez', 0),
(12, 'Cristina', 'Escudero', 11, 'Calle 334', 'Julia Escudero', 'Víctor Escudero', 1),
(12, 'Ángela', 'Esparza', 11, 'Calle 445', 'Monica Esparza', 'Adrián Esparza', 0),
(12, 'Eva', 'Esteban', 11, 'Calle 556', 'Alicia Esteban', 'Ignacio Esteban', 1),
(12, 'Julia', 'Fajardo', 11, 'Calle 667', 'Sara Fajardo', 'Alberto Fajardo', 0),
(12, 'Monica', 'Fernández', 11, 'Calle 778', 'Verónica Fernández', 'Ricardo Fernández', 1),
(12, 'Alicia', 'Ferrán', 11, 'Calle 889', 'Lidia Ferrán', 'Guillermo Ferrán', 0),
(12, 'Sara', 'Figueroa', 11, 'Calle 990', 'Natalia Figueroa', 'Óscar Figueroa', 1),

-- Grado 7: Mañana (9 varones, 10 mujeres)
(14, 'Marcos', 'Flores', 12, 'Calle 101', 'Beatriz Flores', 'Marcos Flores Sr', 0),
(14, 'Julián', 'Font', 12, 'Calle 212', 'Alba Font', 'Julián Font Sr', 1),
(14, 'Rodrigo', 'Fraile', 12, 'Calle 323', 'Clara Fraile', 'Rodrigo Fraile Sr', 0),
(14, 'Federico', 'Fuentes', 12, 'Calle 434', 'Rosa Fuentes', 'Federico Fuentes Sr', 1),
(14, 'Hugo', 'Gámez', 12, 'Calle 545', 'Nuria Gámez', 'Hugo Gámez Sr', 0),
(14, 'Iván', 'Gallo', 12, 'Calle 656', 'Cristina Gallo', 'Iván Gallo Sr', 1),
(14, 'Gabriel', 'Galván', 12, 'Calle 767', 'Ángela Galván', 'Gabriel Galván Sr', 0),
(14, 'Raúl', 'Garrido', 12, 'Calle 878', 'Eva Garrido', 'Raúl Garrido Sr', 1),
(14, 'Mario', 'Gimeno', 12, 'Calle 989', 'Julia Gimeno', 'Mario Gimeno Sr', 0),
(14, 'Inés', 'Girón', 12, 'Calle 111', 'Monica Girón', 'Marcos Girón', 1),
(14, 'Olga', 'Gracia', 12, 'Calle 222', 'Alicia Gracia', 'Julián Gracia', 0),
(14, 'Irene', 'Granados', 12, 'Calle 333', 'Sara Granados', 'Rodrigo Granados', 1),
(14, 'Marina', 'Guijarro', 12, 'Calle 444', 'Verónica Guijarro', 'Federico Guijarro', 0),
(14, 'Esther', 'Heredia', 12, 'Calle 555', 'Lidia Heredia', 'Hugo Heredia', 1),
(14, 'Pilar', 'Hernando', 12, 'Calle 666', 'Natalia Hernando', 'Iván Hernando', 0),
(14, 'Jimena', 'Hervás', 12, 'Calle 777', 'Beatriz Hervás', 'Gabriel Hervás', 1),
(14, 'Raquel', 'Hurtado', 12, 'Calle 888', 'Alba Hurtado', 'Raúl Hurtado', 0),
(14, 'Teresa', 'Ibáñez', 12, 'Calle 999', 'Clara Ibáñez', 'Mario Ibáñez', 1),
(14, 'Angela', 'Infante', 12, 'Calle 121', 'Rosa Infante', 'Marcos Infante', 0);

-- -----------------------------------------------------
-- Datos para tabla `asistencias` (1 día lectivo - 253 registros)
-- -----------------------------------------------------
INSERT INTO asistencias (fecha, id_grado, id_estudiante, tipo_asistencia) VALUES
('2024-04-01', 1, 1, 'Presente'),
('2024-04-01', 1, 2, 'Ausente'),
('2024-04-01', 1, 3, 'Llegada tarde'),
('2024-04-01', 1, 4, 'Presente'),
('2024-04-01', 1, 5, 'Presente'),
('2024-04-01', 1, 6, 'Presente'),
('2024-04-01', 1, 7, 'Presente'),
('2024-04-01', 1, 8, 'Ausente'),
('2024-04-01', 1, 9, 'Presente'),
('2024-04-01', 1, 10, 'Presente'),
-- ... (los 243 registros restantes de asistencias para esta fecha) ...
('2024-04-01', 14, 253, 'Presente');

-- -----------------------------------------------------
-- Datos para tabla `notas` (1265 registros - 5 por estudiante)
-- -----------------------------------------------------
-- Notas para el estudiante 1
INSERT INTO notas (anio, bimestre, id_estudiante, id_grado) VALUES
(2024, 'Primer bimestre', 1, 1),
(2024, 'Segundo bimestre', 1, 1),
(2024, 'Tercer bimestre', 1, 1),
(2024, 'Cuarto bimestre', 1, 1),
(2025, 'Primer bimestre', 1, 1);

-- Notas para el estudiante 2
INSERT INTO notas (anio, bimestre, id_estudiante, id_grado) VALUES
(2024, 'Primer bimestre', 2, 1),
(2024, 'Segundo bimestre', 2, 1),
(2024, 'Tercer bimestre', 2, 1),
(2024, 'Cuarto bimestre', 2, 1),
(2025, 'Primer bimestre', 2, 1);

-- ... (continuar con el mismo patrón para los 251 estudiantes restantes) ...

-- Notas para el estudiante 253
INSERT INTO notas (anio, bimestre, id_estudiante, id_grado) VALUES
(2024, 'Primer bimestre', 253, 14),
(2024, 'Segundo bimestre', 253, 14),
(2024, 'Tercer bimestre', 253, 14),
(2024, 'Cuarto bimestre', 253, 14),
(2025, 'Primer bimestre', 253, 14);